### ISSUE TITLE
Error: Running the contributed command:'extension.exportAll' failed.

### ISSUE THREAD

**Issue by sladiri** [golf1052/code-sync#11]
I cannot export, I am using Windows 10. I did not change the default Onedrive folder location after install. 

**edit:**
I was able to workaround like this:
When I got the prompt for the sync location, I deleted the last letter and reinserted it again in the input field. There was no error then.

**Comment by golf1052** [comment]
Looks like this is related to [this issue](https://github.com/Microsoft/vscode/issues/11503). I'm also going to add another command (CodeSync: Set external sync path) so that you can change the sync path without uninstalling and reinstalling the extension.

**Comment by golf1052** [comment]
This has been fixed in VSCode 1.6.0: https://github.com/Microsoft/vscode/issues/11503
