### ISSUE TITLE
Import extensions command has no effect

### ISSUE THREAD

**Issue by aga5tya** [golf1052/code-sync#12]
I exported all the settings, extensions etc to a folder and then i imported the files onto a folder on a different system. The VS code asks for the path to set, and then i run import all command. Settings and snippets get synced, but i see no effect over extensions being imported and there is no progress status visible anywhere as such. Let me know if i can be of any help in providing logs.

Operating System: OSX Sierra
VSCode: 1.5.3
CodeSync: 2.0.0

**Comment by golf1052** [comment]
Have you still been experiencing this issue?

**Comment by golf1052** [comment]
2.4.0 has added logging. After upgrading to 2.4.0 if you still experience this issue please reopen this issue and paste your log here. Thanks.
