### ISSUE TITLE
Can't set path on Mac

### ISSUE THREAD

**Issue by arpo** [golf1052/code-sync#14]
This extension works like a charm on my PC but not on my Mac. 
When restarting VS Code after instralling the extansion it say that it can't find the path in stead of prompting me to define it. 
When trying to set it via the command pallet it says:

Error: command 'extension.setSyncPath' not found

**Comment by russellseymour** [comment]
I have just installed the extension on my Mac and I was not given the opportunity to set the path either - I was not prompted.
Is this in settings somewhere so I can set it manually?

**Comment by golf1052** [comment]
@russellseymour Do you mean setting the VS Code path or setting CodeSync's external sync path.
For VS Code - https://code.visualstudio.com/docs/setup/mac
For CodeSync's external sync path in the command palette look for `CodeSync: Set external sync path`

**Comment by piggyslasher** [comment]
Same here.

**Comment by guillaumemolter** [comment]
Same here, I installed the extension, restarted Code VS and got an error message saying CodeSync couldn't sync my code.

The current documentation reads: "VSCode will now prompt for the folder to where you want sync extensions. This should be a folder that syncs to your other computers.". I was not prompted and couldn't find anything in preferences to set the path.

The command you are referring to, while existing throws the error described by @piggyslasher. And is not listed in the documentation under "Commands".

Hope it helps.

Using MacOS 10.12 Code 1.9.1.

**Comment by colthreepv** [comment]
same on windows 10 x64 + vscode 1.10

**Comment by brandoncc** [comment]
I have the same problem. It seems like the commands are intermittently available, and it seems like they are only available if there is a file open in my workspace.

**Comment by nazimjamil** [comment]
If you're still experiencing this issue on OSX, install Code command line path and then attempt to set the path. Worked for me.. https://code.visualstudio.com/docs/setup/mac

**Comment by golf1052** [comment]
Just released CodeSync 2.3.0 which allows you to use the rest of the extension even if CodeSync thinks `code` isn't on your path.

Also closing this issue in favor of https://github.com/golf1052/code-sync/issues/9
