### ISSUE TITLE
Suggestion: a list of settings to exclude from sync

### ISSUE THREAD

**Issue by drdaeman** [golf1052/code-sync#17]
I'd propose an enhancement - some way to not sync certain settings, but sync others.

My use case is, I have two machines with different display DPIs. The only reliable way I found to handle it with VSCode is manually configuring things `window.zoomLevel` setting. However, since the setting is saved, either UI becomes tiny on the HiDPI laptop, or a low-DPI desktop gets giant fonts and widgets.

Another use case would be filesystem paths, which may differ on different machines.

My general suggestion is to have a list of settings exempt from syncing, and when they're updated - always take values from local config.

**Comment by golf1052** [comment]
Added with https://github.com/golf1052/code-sync/pull/22
