### ISSUE TITLE
Stalls on 'Importing Settings'

### ISSUE THREAD

**Issue by nazimjamil** [golf1052/code-sync#24]
Using the latest version of code-sync and VS Code, I set my Dropbox location for sync'd components. The UI then shows CodeSync status as Importing settings, indefinitely.

Have completely removed VS Code and all associated files and reinstalled, however the issue still persists.

OS/ Mac OS Sierra (10.12.4)

**Comment by golf1052** [comment]
Pushed 2.3.2 which should fix this issue. Just realized that I actually never pushed it.
Also going to add logging to the next version so any other issues that come up will be easier to debug.

**Comment by golf1052** [comment]
Pushed 2.4.0 which adds logging. If you are still experiencing this issue after upgrading to 2.4.0 please paste your CodeSync log here.
