### ISSUE TITLE
Setting to Hide Status Bar Icon

### ISSUE THREAD

**Issue by gnowland** [golf1052/code-sync#25]
Hi Sanders, thanks for your awesome work on this plugin.

I know you recently added support for the status bar but mine is getting a little crowded and forcing some stuff to hide... would you be able to add a setting to allow hiding of the status bar icon for your extension?

This would be super awesome!!

Thank you.

**Comment by golf1052** [comment]
Added with version 2.4.0. Thanks for the suggestion.
