### ISSUE TITLE
issue of 'upload to gist' function

### ISSUE THREAD

**Issue by tkddn204** [golf1052/code-sync#33]
- VSCode version: 1.30.2

- CodeSync version: 3. 2.4

- CodeSync log:
```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303 [Extension Host] HttpError: Not Found
    at module.exports.e.exports.i.fetch.then.n.text.then.n (C:\Users\user\.vscode\extensions\shan.code-settings-sync-3.2.4\out\extension.js:137:45419)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
t.log @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:303

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2508 Sync : Error Logged In Console (Help menu > Toggle Developer Tools).
t.onDidNotificationChange @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:2508
```
![what](https://user-images.githubusercontent.com/6284140/51087146-778e7680-1792-11e9-8bfd-36ccc622c4dc.png)

- Issue: 
when I tryed gist upload, I saw these messages.
what happened to codesync??

**Comment by golf1052** [comment]
The extension you're referring to is Settings Sync. Their repo is available [here](https://github.com/shanalikhan/code-settings-sync).

CodeSync doesn't have an "upload to gist" function. CodeSync only uses file synchronization services to sync.

**Comment by tkddn204** [comment]
sorry for my mistake
