### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Chusynuk** [golf1052/code-sync#34]
- Issue Type: `Performance`
- Extension Name: `code-sync`
- Extension Version: `2.5.3`
- OS Version: `Darwin x64 18.6.0`
- VSCode version: `1.36.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/eloi/golf1052.code-sync-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by golf1052** [comment]
Can you attach the `golf1052.code-sync-unresponsive.cpuprofile.txt` file to this issue?

**Comment by golf1052** [comment]
I've updated chokidar to version 3 which should provide considerable performance improvements.
