### ISSUE TITLE
Publish the extension to OpenVSX

### ISSUE THREAD

**Issue by ahaasler** [golf1052/code-sync#44]
Hi, I'm a [VSCodium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code. It's the same code but without Microsoft's telemetry, branding and licensing.

I would like to request, if possible, to add the CodeSync for VSCode extension to the [open-vsx.org](https://open-vsx.org/) market as it is unclear if it's legal to use the official Microsoft extension marketplace on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional information on how to publish an extension to Open VSX can be obtained [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

**Comment by golf1052** [comment]
Now published on Open VSX https://open-vsx.org/extension/golf1052/code-sync

Thanks for the suggestion!
