### ISSUE TITLE
Error when exporting extensions

### ISSUE THREAD

**Issue by fastest963** [golf1052/code-sync#7]
When I try and Export Extensions (from the Ctrl+Shift+P menu) it gives an error `Cannot read property 'themes' of undefined` and no extensions are saved. I only recently started getting this and I tried uninstalling and re-installing extensions to figure out which one caused it but I can't seem to find any that might've caused it.

**Comment by fastest963** [comment]
If it helps, I haven't ever installed any themes or anything and I have the default theme.

**Comment by golf1052** [comment]
I've been planning to upgrade this. I wrote it when VSCode was version 0.10.1 and now they just hit 1.0.0. It will probably take a little while to get everything in order.

I heard [this](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) extension is pretty good for syncing things.

**Comment by viktor-ferenczi** [comment]
Visual Studio 1.1.0

Configured OneDrive folder.

Tried command: CodeSync: Export extensions

Got this error message: "No handler found for the command: 'extension.exportExtensions'. An extension might be missing an activation event."

**Comment by golf1052** [comment]
I have rewritten the extension (it's way better now). If you have any more problems after upgrading feel free to create another issue.
